= Pkl Documentation Website image:https://badges.pie.apple.com/badges/rio?p=pie-pcl-docsite&s=pie-pcl-docsite-publish&l=Build[link="https://rio.apple.com/projects/pie-pcl-docsite"]

Repo for Pkl's https://pkl.apple.com[documentation website].

The website is built with the https://antora.org[Antora] docsite generator out of https://asciidoctor.org[Asciidoc] docs maintained in upstream projects (pkl, pkl-spring, etc.).

== Development

=== Releases

For a new release of the website, run the https://rio.apple.com/projects/aci-pkl-pkl-docsite/pipeline-specs/aci-pkl-pkl-docsite-publish/pipelines[`publish` pipeline in Rio].

=== Install dependencies

[source,shell]
----
$ ./gradlew downloadPklHtmlHighlighter npmInstall
----

=== Build Docs of Local Projects

* Takes upstream project docs from local Git repos assumed to be siblings of this repo (see _site-local.yml_).
* Builds the site (click the link printed in console output to open in browser).

This allows to preview local doc changes made to upstream projects.

[source,shell]
----
$ ./gradlew buildLocalSite   # shorthand: gw bLS
----

=== Validate Docs of Local Projects

* Validates HTML
* Checks for dangling links

[source,shell]
----
$ ./gradlew validateLocalSite   # shorthand: gw vLS
----

=== Build Docs of Remote Projects

* Fetches upstream project docs from their GitHub repos (see _site-remote.yml_).
* Builds the site (click the link printed in console output to open in browser).

This is what CI runs.

[source,shell]
----
$ ./gradlew buildRemoteSite   # shorthand: gw bRS
----

To run this task locally, you must have the following in place:

.~/.git-credentials
[source]
----
https://GITHUB_ACCESS_TOKEN@github.pie.apple.com
----

In the above, `GITHUB_ACCESS_TOKEN` is a GitHub personal access token with scope `public_repo`.

=== Validate Docs of Remote Projects

* Validates HTML
* Checks for dangling links

[source,shell]
----
$ ./gradlew validateRemoteSite   # shorthand: gw vRS
----
